sudo: required

language: go

branches:
  only:
    - master
go:
  - 1.6.3
  - 1.7.1
  - tip

env:
  global:
    - GOARCH=amd64
    - BLAS_LIB=OpenBLAS
    - TRAVISTEST=true

# Cache used to persist the compiled BLAS library between CI calls.
cache:
  directories:
  - .travis/OpenBLAS.cache

before_install:
  - go get github.com/mattn/goveralls

# Install the appropriate blas library (if any) and associated gonum software.
install:
- source ${TRAVIS_BUILD_DIR}/.travis/$TRAVIS_OS_NAME/$BLAS_LIB/install.sh

script: 
- source ${TRAVIS_BUILD_DIR}/.travis/$TRAVIS_OS_NAME/$BLAS_LIB/test.sh